Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/03/2024
Var
// Seção de Declarações das variáveis 
n1, n2, r: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Dígite dois números")
leia (n1)
leia (n2)
r <-n1 * n2
escreval ("A multiplicação é: ", r)
Fimalgoritmo