Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/03/2024
Var
n1, n2, d:real

Inicio
escreval("Dígite dois números:")
leia (n1)
leia (n2)
se n2 = 0 entao
escreval ("Impossivel dividir")
senao
d <- n1/n2
escreval(d)
fimse

Fimalgoritmo