Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/03/2024
Var
n1, n2, m:real

Inicio
escreval ("Vamos calcular a média das suas notas, digite sua nota 1")
leia (n1)
escreval ("agora sua nota 2")
leia (n2)
m<-(n1+n2)/2
escreval ("Sua média de notas é de", m)

Fimalgoritmo