Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/03/2024
Var
num, x, m, idade:inteiro,

Inicio
para m de 0 ate 100 passo 20 faca
se (m<>0) entao
   escreval ("Multiplo de 20 = ", m)
   fimse
   fimpara

Fimalgoritmo